# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d3cd7910372c8c91b0300a824f385f1dadff337d13aeb02e02699f412106882d1cebd7ee7fc84d621078e90b1720cebbcd9d2d479b8e152aa9db2a10bb5cada

test:
  secret_key_base: d748a1c0544601618fb3a5bef048fb0acd58a057e819e7e873876b2a474f39df2bb0050cf81b81672a4248e0f9df18ae7500c9c245eff1b8da3ad8d088e7ba38

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
